version: '3.8'

services:
  rag-pipeline:
    build: .
    container_name: faiss-rag-pipeline
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      # Mount your data directory
      - ./data:/app/data
      # Mount your models directory
      - ./models:/app/models
      # Mount vector store for persistence
      - ./vector_store:/app/vector_store
      # Optional: Mount source code for development
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000